In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.float_format', lambda x: f'{x:.2f}')
pd.set_option('display.max_columns', None)

In [2]:
df_original = pd.read_csv("Housing.csv")
df = df_original.copy()

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7229300521,20141013T000000,231300.00,2,1.00,1180,5650,1.00,0,0,3,7,1180,0,1955,0,98178,47.51,-122.26,1340,5650
1,6414100192,20141209T000000,538000.00,3,2.25,2570,7242,2.00,0,0,3,7,2170,400,1951,1991,98125,47.72,-122.32,1690,7639
2,5631500400,20150225T000000,180000.00,2,1.00,770,10000,1.00,0,0,3,6,770,0,1933,0,98028,47.74,-122.23,2720,8062
3,2487200875,20141209T000000,604000.00,4,3.00,1960,5000,1.00,0,0,5,7,1050,910,1965,0,98136,47.52,-122.39,1360,5000
4,1954400510,20150218T000000,510000.00,3,2.00,1680,8080,1.00,0,0,3,8,1680,0,1987,0,98074,47.62,-122.05,1800,7503

In [4]:
df.columns.tolist()

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [6]:
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00,21613.00
mean,4580306147.71,540088.58,3.37,2.11,2079.90,15106.97,1.49,0.01,0.23,3.41,7.66,1788.39,291.51,1971.01,84.40,98077.94,47.56,-122.21,1986.55,12768.46
std,2876569751.89,367126.83,0.93,0.77,918.44,41420.51,0.54,0.09,0.77,0.65,1.18,828.09,442.58,29.37,401.68,53.51,0.14,0.14,685.39,27304.18
min,1000102.00,75000.00,0.00,0.00,290.00,520.00,1.00,0.00,0.00,1.00,1.00,290.00,0.00,1900.00,0.00,98001.00,47.16,-122.52,399.00,651.00
25%,2123049194.00,321950.00,3.00,1.75,1427.00,5040.00,1.00,0.00,0.00,3.00,7.00,1190.00,0.00,1951.00,0.00,98033.00,47.47,-122.33,1490.00,5100.00
50%,3904930410.00,450000.00,3.00,2.25,1910.00,7618.00,1.50,0.00,0.00,3.00,7.00,1560.00,0.00,1975.00,0.00,98065.00,47.57,-122.23,1840.00,7620.00
75%,7308900445.00,645000.00,4.00,2.50,2550.00,10688.00,2.00,0.00,0.00,4.00,8.00,2210.00,560.00,1997.00,0.00,98118.00,47.68,-122.12,2360.00,10083.00
max,9900000190.00,7700000.00,33.00,8.00,13540.00,1651359.00,3.50,1.00,4.00,5.00,13.00,9410.00,4820.00,2015.00,2015.00,98199.00,47.78,-121.31,6210.00,871200.00

In [7]:
df = df.drop(columns=["id"])

In [8]:
num_col = ["price","sqft_living","sqft_lot","sqft_above","sqft_basement","lat","long","sqft_living15","sqft_lot15","bedrooms","bathrooms","floors",]
cat_col = ["waterfront","view","condition","grade","zipcode"]
date_col = ["date","yr_built","yr_renovated"]

 'date' - has impact. can deduce current price based on price on this date,
 'price',
 'bedrooms' = more bedrooms will lead to more price,
 'bathrooms' = more bathrooms more price,
 'sqft_living' = more sqft living more price,
 'sqft_lot' = more sqft lot more price,
 'floors' = more floors more price,
 'waterfront' = more waterfront more price,
 'view' = higher view more price,
 'condition' = greater confition more price,
 'grade' = gretaer grade more price,
 'sqft_above' = more sqft_above more price,
 'sqft_basement' = more sqft_basement more price,
 'yr_built' = latest built more price,
 'yr_renovated' = recent renovated more price,
 'zipcode' = does not indicate locality, should have minimum impact since model wont understand locality from this ,
 'lat' = does not indicate locality, should have minimum impact since model wont understand locality from this,
 'long' = does not indicate locality, should have minimum impact since model wont understand locality from this,
 'sqft_living15' = if greater than this house sqft_living less price,
 'sqft_lot15 ' = if greater than this house sqft lot less price

In [9]:
df["date"] = df["date"].str.replace("T000000","")
df.corr()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
date,1.00,0.00,-0.01,-0.03,-0.03,0.01,-0.02,-0.00,0.00,-0.05,-0.03,-0.02,-0.02,0.00,-0.02,0.00,-0.03,-0.00,-0.02,0.00
price,0.00,1.00,0.31,0.53,0.70,0.09,0.26,0.27,0.40,0.04,0.67,0.61,0.32,0.05,0.13,-0.05,0.31,0.02,0.59,0.08
bedrooms,-0.01,0.31,1.00,0.52,0.58,0.03,0.18,-0.01,0.08,0.03,0.36,0.48,0.30,0.15,0.02,-0.15,-0.01,0.13,0.39,0.03
bathrooms,-0.03,0.53,0.52,1.00,0.75,0.09,0.50,0.06,0.19,-0.12,0.66,0.69,0.28,0.51,0.05,-0.20,0.02,0.22,0.57,0.09
sqft_living,-0.03,0.70,0.58,0.75,1.00,0.17,0.35,0.10,0.28,-0.06,0.76,0.88,0.44,0.32,0.06,-0.20,0.05,0.24,0.76,0.18
sqft_lot,0.01,0.09,0.03,0.09,0.17,1.00,-0.01,0.02,0.07,-0.01,0.11,0.18,0.02,0.05,0.01,-0.13,-0.09,0.23,0.14,0.72
floors,-0.02,0.26,0.18,0.50,0.35,-0.01,1.00,0.02,0.03,-0.26,0.46,0.52,-0.25,0.49,0.01,-0.06,0.05,0.13,0.28,-0.01
waterfront,-0.00,0.27,-0.01,0.06,0.10,0.02,0.02,1.00,0.40,0.02,0.08,0.07,0.08,-0.03,0.09,0.03,-0.01,-0.04,0.09,0.03
view,0.00,0.40,0.08,0.19,0.28,0.07,0.03,0.40,1.00,0.05,0.25,0.17,0.28,-0.05,0.10,0.08,0.01,-0.08,0.28,0.07
condition,-0.05,0.04,0.03,-0.12,-0.06,-0.01,-0.26,0.02,0.05,1.00,-0.14,-0.16,0.17,-0.36,-0.06,0.00,-0.01,-0.11,-0.09,-0.00
grade,-0.03,0.67,0.36,0.66,0.76,0.11,0.46,0.08,0.25,-0.14,1.00,0.76,0.17,0.45,0.01,-0.18,0.11,0.20,0.71,0.12
sqft_above,-0.02,0.61,0.48,0.69,0.88,0.18,0.52,0.07,0.17,-0.16,0.76,1.00,-0.05,0.42,0.02,-0.26,-0.00,0.34,0.73,0.19
sqft_basement,-0.02,0.32,0.30,0.28,0.44,0.02,-0.25,0.08,0.28,0.17,0.17,-0.05,1.00,-0.13,0.07,0.07,0.11,-0.14,0.20,0.02
yr_built,0.00,0.05,0.15,0.51,0.32,0.05,0.49,-0.03,-0.05,-0.36,0.45,0.42,-0.13,1.00,-0.22,-0.35,-0.15,0.41,0.33,0.07
yr_renovated,-0.02,0.13,0.02,0.05,0.06,0.01,0.01,0.09,0.10,-0.06,0.01,0.02,0.07,-0.22,1.00,0.06,0.03,-0.07,-0.00,0.01
zipcode,0.00,-0.05,-0.15,-0.20,-0.20,-0.13,-0.06,0.03,0.08,0.00,-0.18,-0.26,0.07,-0.35,0.06,1.00,0.27,-0.56,-0.28,-0.15
lat,-0.03,0.31,-0.01,0.02,0.05,-0.09,0.05,-0.01,0.01,-0.01,0.11,-0.00,0.11,-0.15,0.03,0.27,1.00,-0.14,0.05,-0.09
long,-0.00,0.02,0.13,0.22,0.24,0.23,0.13,-0.04,-0.08,-0.11,0.20,0.34,-0.14,0.41,-0.07,-0.56,-0.14,1.00,0.33,0.25
sqft_living15,-0.02,0.59,0.39,0.57,0.76,0.14,0.28,0.09,0.28,-0.09,0.71,0.73,0.20,0.33,-0.00,-0.28,0.05,0.33,1.00,0.18
sqft_lot15,0.00,0.08,0.03,0.09,0.18,0.72,-0.01,0.03,0.07,-0.00,0.12,0.19,0.02,0.07,0.01,-0.15,-0.09,0.25,0.18,1.00

In [10]:
df["house_age"] = 2026 - df["yr_built"]

In [11]:
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,house_age
0,20141013,231300.00,2,1.00,1180,5650,1.00,0,0,3,7,1180,0,1955,0,98178,47.51,-122.26,1340,5650,71
1,20141209,538000.00,3,2.25,2570,7242,2.00,0,0,3,7,2170,400,1951,1991,98125,47.72,-122.32,1690,7639,75
2,20150225,180000.00,2,1.00,770,10000,1.00,0,0,3,6,770,0,1933,0,98028,47.74,-122.23,2720,8062,93
3,20141209,604000.00,4,3.00,1960,5000,1.00,0,0,5,7,1050,910,1965,0,98136,47.52,-122.39,1360,5000,61
4,20150218,510000.00,3,2.00,1680,8080,1.00,0,0,3,8,1680,0,1987,0,98074,47.62,-122.05,1800,7503,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,20140521,360000.00,3,2.50,1530,1131,3.00,0,0,3,8,1530,0,2009,0,98103,47.70,-122.35,1530,1509,17
21609,20150223,400000.00,4,2.50,2310,5813,2.00,0,0,3,8,2310,0,2014,0,98146,47.51,-122.36,1830,7200,12
21610,20140623,402101.00,2,0.75,1020,1350,2.00,0,0,3,7,1020,0,2009,0,98144,47.59,-122.30,1020,2007,17
21611,20150116,400000.00,3,2.50,1600,2388,2.00,0,0,3,8,1600,0,2004,0,98027,47.53,-122.07,1410,1287,22
21612,20141015,325000.00,2,0.75,1020,1076,2.00,0,0,3,7,1020,0,2008,0,98144,47.59,-122.30,1020,1357,18

In [12]:
df["renovated"] = np.where(df["yr_renovated"] != 0, 1,0)

In [13]:
df["sale_month"] = df["date"].str.slice(4,6)

In [14]:
df = df.drop(columns=["zipcode","yr_built","yr_renovated","date","sqft_above"])

In [15]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,renovated,sale_month
0,231300.00,2,1.00,1180,5650,1.00,0,0,3,7,0,47.51,-122.26,1340,5650,71,0,10
1,538000.00,3,2.25,2570,7242,2.00,0,0,3,7,400,47.72,-122.32,1690,7639,75,1,12
2,180000.00,2,1.00,770,10000,1.00,0,0,3,6,0,47.74,-122.23,2720,8062,93,0,02
3,604000.00,4,3.00,1960,5000,1.00,0,0,5,7,910,47.52,-122.39,1360,5000,61,0,12
4,510000.00,3,2.00,1680,8080,1.00,0,0,3,8,0,47.62,-122.05,1800,7503,39,0,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.00,3,2.50,1530,1131,3.00,0,0,3,8,0,47.70,-122.35,1530,1509,17,0,05
21609,400000.00,4,2.50,2310,5813,2.00,0,0,3,8,0,47.51,-122.36,1830,7200,12,0,02
21610,402101.00,2,0.75,1020,1350,2.00,0,0,3,7,0,47.59,-122.30,1020,2007,17,0,06
21611,400000.00,3,2.50,1600,2388,2.00,0,0,3,8,0,47.53,-122.07,1410,1287,22,0,01
21612,325000.00,2,0.75,1020,1076,2.00,0,0,3,7,0,47.59,-122.30,1020,1357,18,0,10

In [16]:
df.columns.tolist()

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_basement',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15',
 'house_age',
 'renovated',
 'sale_month']

In [17]:
X = df.drop(columns="price")
y = df["price"]

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [20]:
lr.fit(X_train,y_train)

LinearRegression()

In [21]:
y_pred = lr.predict(X_test)

In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,root_mean_squared_error

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print("MAE - ",mae)
print("MSE - ",mse)
print("RMSE - ",rmse)
print("R2 Score - ",r2)

MAE -  127738.79198182606
MSE -  45908771016.46378
RMSE -  214263.32167793857
R2 Score -  0.6963237900129582

In [23]:
from sklearn.tree import DecisionTreeRegressor

dtr = DecisionTreeRegressor()

In [24]:
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [25]:
y_pred = dtr.predict(X_test)

In [26]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print("MAE - ",mae)
print("MSE - ",mse)
print("RMSE - ",rmse)
print("R2 Score - ",r2)

MAE -  102732.83576220217
MSE -  44037719876.50312
RMSE -  209851.66160052945
R2 Score -  0.7087003730992583

In [27]:
from sklearn.ensemble import RandomForestRegressor

rfr = RandomForestRegressor()

In [28]:
rfr.fit(X_train,y_train)

RandomForestRegressor()

In [29]:
y_pred = rfr.predict(X_test)

In [30]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print("MAE - ",mae)
print("MSE - ",mse)
print("RMSE - ",rmse)
print("R2 Score - ",r2)

MAE -  72975.31865371269
MSE -  21551510107.116413
RMSE -  146804.32591417874
R2 Score -  0.8574416007241952

In [31]:
rfr.feature_importances_

array([0.00286427, 0.01344955, 0.25253127, 0.01522012, 0.00234767,
       0.03125044, 0.01068243, 0.00308109, 0.34162027, 0.00893151,
       0.15684835, 0.06758992, 0.03435118, 0.01466895, 0.03639963,
       0.00118088, 0.00698248])

In [32]:
feature_importance  = pd.DataFrame({
    'feature': X_train.columns,
    'importance': rfr.feature_importances_*100
})

feature_importance = feature_importance.sort_values(by='importance',ascending=False)
print(feature_importance)

          feature  importance
8           grade       34.16
2     sqft_living       25.25
10            lat       15.68
11           long        6.76
14      house_age        3.64
12  sqft_living15        3.44
5      waterfront        3.13
3        sqft_lot        1.52
13     sqft_lot15        1.47
1       bathrooms        1.34
6            view        1.07
9   sqft_basement        0.89
16     sale_month        0.70
7       condition        0.31
0        bedrooms        0.29
4          floors        0.23
15      renovated        0.12

In [33]:
rfr1 = RandomForestRegressor(n_estimators=100,max_depth=39,min_samples_split=10)

In [34]:
rfr1.fit(X_train,y_train)

RandomForestRegressor(max_depth=39, min_samples_split=10)

In [35]:
y_pred = rfr1.predict(X_test)

In [36]:
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)

print("MAE - ",mae)
print("MSE - ",mse)
print("RMSE - ",rmse)
print("R2 Score - ",r2)

MAE -  73720.1566504762
MSE -  21509272299.540688
RMSE -  146660.39785688804
R2 Score -  0.8577209943354543

In [37]:
feature_importance  = pd.DataFrame({
    'feature': X_train.columns,
    'importance': rfr1.feature_importances_*100
})

feature_importance = feature_importance.sort_values(by='importance',ascending=False)
print(feature_importance)

          feature  importance
8           grade       35.13
2     sqft_living       26.55
10            lat       15.75
11           long        6.58
14      house_age        3.50
5      waterfront        3.21
12  sqft_living15        3.19
3        sqft_lot        1.22
13     sqft_lot15        1.17
1       bathrooms        0.99
6            view        0.94
9   sqft_basement        0.66
16     sale_month        0.44
7       condition        0.23
0        bedrooms        0.20
4          floors        0.15
15      renovated        0.09

In [38]:
results = X_test.copy()

results["actual"]=y_test
results["predicted"]=y_pred

In [39]:
results.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,renovated,sale_month,actual,predicted
735,4,2.25,2070,8893,2.00,0,0,4,8,0,47.44,-122.16,2390,7700,40,0,10,365000.00,383227.22
2830,5,3.00,2900,6730,1.00,0,0,5,8,1070,47.68,-122.28,2370,6283,49,0,08,865000.00,930744.15
4106,4,2.50,3770,10893,2.00,0,2,3,11,0,47.56,-122.13,3710,9685,29,0,08,1038000.00,1091658.98
16218,3,3.50,4560,14608,2.00,0,2,3,12,0,47.70,-122.23,4050,14226,36,0,03,1490000.00,1990845.69
19964,3,2.50,2550,5376,2.00,0,0,3,9,0,47.66,-122.08,2250,4050,22,0,07,711000.00,707576.30

In [40]:
results["error"] = results["actual"] - results["predicted"]
results["abs_error"] = abs(results["error"])

In [41]:
results.sort_values(by='abs_error',ascending=False).head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,renovated,sale_month,actual,predicted,error,abs_error
12777,7,8.00,13540,307752,3.00,0,4,3,12,4130,47.67,-121.99,4850,217800,27,0,05,2280000.00,5133194.26,-2853194.26,2853194.26
4024,7,6.75,7480,41664,2.00,0,2,3,11,2400,47.46,-122.37,2810,33190,73,0,10,800000.00,3372329.70,-2572329.70,2572329.70
14556,5,6.25,8670,64033,2.00,0,4,3,13,2550,47.73,-122.37,4140,81021,61,1,06,2888000.00,4685772.84,-1797772.84,1797772.84
21050,5,6.00,7120,40806,2.00,0,4,3,12,1640,47.55,-122.11,3440,36859,19,0,02,900000.00,2430824.85,-1530824.85,1530824.85
2085,4,4.25,5770,21300,2.00,1,4,4,11,0,47.59,-122.22,4620,22748,46,0,11,3850000.00,2368503.16,1481496.84,1481496.84

In [42]:
results.sort_values(by='abs_error',ascending=True).head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,renovated,sale_month,actual,predicted,error,abs_error
10369,2,1.00,2140,6000,1.00,0,0,4,7,1070,47.65,-122.40,1560,6000,80,0,05,680000.00,680022.02,-22.02,22.02
180,3,2.50,1670,5797,2.00,0,0,3,7,0,47.35,-122.18,1670,6183,38,0,07,260000.00,260025.93,-25.93,25.93
17669,3,2.25,1840,5752,2.00,0,0,3,7,0,47.70,-122.19,1670,2462,23,0,05,465000.00,464970.25,29.75,29.75
4072,3,1.50,860,3200,1.00,0,0,3,6,0,47.68,-122.36,1220,4300,97,0,04,445000.00,445031.93,-31.93,31.93
19762,4,2.00,1350,942,3.00,0,0,3,7,0,47.54,-122.03,1390,942,18,0,03,304500.00,304546.53,-46.53,46.53

In [43]:
results["error"].describe()

count       4323.00
mean        -161.05
std       146677.28
min     -2853194.26
25%       -43280.95
50%        -2751.96
75%        36753.82
max      1481496.84
Name: error, dtype: float64

In [44]:
results["error"].mean()

np.float64(-161.04905333650294)

In [45]:
import joblib

joblib.dump({
    "model": rfr1,
    "features": X.columns.tolist()
}, "house_price_pipeline.pkl")

['house_price_pipeline.pkl']

In [50]:
results[results["actual"]<600000].sort_values(by='abs_error',ascending=True).head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_basement,lat,long,sqft_living15,sqft_lot15,house_age,renovated,sale_month,actual,predicted,error,abs_error
180,3,2.50,1670,5797,2.00,0,0,3,7,0,47.35,-122.18,1670,6183,38,0,07,260000.00,260025.93,-25.93,25.93
17669,3,2.25,1840,5752,2.00,0,0,3,7,0,47.70,-122.19,1670,2462,23,0,05,465000.00,464970.25,29.75,29.75
4072,3,1.50,860,3200,1.00,0,0,3,6,0,47.68,-122.36,1220,4300,97,0,04,445000.00,445031.93,-31.93,31.93
19762,4,2.00,1350,942,3.00,0,0,3,7,0,47.54,-122.03,1390,942,18,0,03,304500.00,304546.53,-46.53,46.53
19111,3,1.75,1420,6984,1.00,0,0,4,7,440,47.37,-122.18,1430,7875,46,0,03,240000.00,240078.14,-78.14,78.14